### ISSUE TITLE
Next batch of patches TODO list

### ISSUE THREAD

**Issue by enumag** [07th-mod/higurashi-patch-compiler#50]
Don't mind me, just writing down a few notes for myself.

- [x] Add new tips unlock screens for Mea and Tsumi.
- [x] Create tips.json files for all chapter.
- [x] Update tips.json for mea and tsumi.
- [x] Update scripts with PS3 opening flags.
- [x] Update init.txt for all chapters to fix font-size in config.
- [x] Compile new UI for all chapters.
- [x] Create new Graphics pack for Meakashi.
- [x] Check missing files for Meakashi.
- [x] Fix names in Hima and Mea (https://github.com/07th-mod/himatsubushi/issues/39).
- [ ] Fix Maebara Manor (https://github.com/07th-mod/onikakushi/issues/178).
- [x] Fix Meakashi ending (https://github.com/07th-mod/meakashi/commit/1e6c9e69631f1c7716b7bd9846cb492f8a063a74#r30949734).
- [x] Fix subject mixup (https://github.com/07th-mod/tatarigoroshi/issues/68).
- [x] Fix Meakashi TIPS 22 (https://github.com/07th-mod/meakashi/blob/master/Update/_meak_tips_22.txt#L100 is replaced by `r…………情報屋の連絡で、裏を取ることができた。やはり、大石の予想通りだった。` on PS3).
- [ ] Fix audio (https://github.com/07th-mod/meakashi/issues/28).
- [ ] Fix bad BGM (https://github.com/07th-mod/meakashi/issues/39).
- [x] Fix Oni fullscreen (https://github.com/07th-mod/higurashi-assembly/issues/12).
- [x] Check issues in all chapters.
- [ ] Add 07-mod logo to all chapters.
- [x] Add mod keys screen to all chapters.
- [x] Write changelog.
