### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by enumag** [07th-mod/higurashi-patch-compiler#6]
Too many things are happening at once so I need to write a list of everything we need take care of.

- [x] Write down a list of new global flags and keys (https://github.com/07th-mod/higurashi-patch-compiler/wiki/Notes)
- [x] Some flags need a way to tell which value they have (like censorship - key wont do anything visible, no way to tell if the flag is active or not)
- [x] Finish Hima with Miyuki (https://github.com/07th-mod/himatsubushi/issues/27)
- [ ] Do missing voices detection for all chapters like we did with Tata
- [x] Update scripts to new DLLs
  - [x] Onikakushi
  - [x] Watanagashi
  - [x] Tatarigoroshi
  - [x] Himatsubushi
  - [x] Meakashi
- [ ] Write down a list of steps to do for every new chapters (commands to run, things to do manually etc.), the process is getting quite complicated with the ADV-mode, PS2 voices and DLL updates, make this as a checkbox list to be used for every new chapter

**Comment by P-Chang** [comment]
Is it enough that system voice says current value when pressing hotkey + another key (like "c" + RightShift )?

**Comment by P-Chang** [comment]
![20170823124847_1](https://user-images.githubusercontent.com/29869319/29601564-2b1ae5ba-8817-11e7-858b-507f54c18e26.jpg)

I made Gflag monitor. What flags that you want to monitoring.

**Comment by enumag** [comment]
@P-Chang Looks great!

**Comment by enumag** [comment]
@ItaloKnox @P-Chang Status update: I just finished tata_009, again fixing some voices and other issues. I played it mostly in auto-mode to test the recent DLL changes. Everything works fine, the game waits for voices as expected. Do you have anything else we should look into before the release? If not I think we can make new releases for all chapters during the next week or two.

**Comment by enumag** [comment]
ping @ItaloKnox @P-Chang

**Comment by ItaloKnox** [comment]
Damn, I completely missed this when you posted, sorry. I guess we'll need to push updates for all chapters again, right? Since we're doing the dll thing, I will also have to update the install scripts and installer exe.

If you think we're ready for production, I want to start pushing them next week. Are we going all the way to ch.5? It's going to be a little troublesome but I want to push all chapters on monday. I have some stuff to do for the rest of the week so I don't want to risk losing a day or two if we release them progressively.

**Comment by enumag** [comment]
Yeah, all chapters need the update. I want a green light from @P-Chang before we make the releases but I think we're ready. I'll write you a list with the necessary steps. If you make all releases at once or not is really up to you.

**Comment by P-Chang** [comment]
I probably finished all that I should do until pre-release.

@ItaloKnox 
Please, re-download entire archive until push, just in case. Because, I often updated them.

http://www.mediafire.com/file/4rt313dr8trawt4/chapter1dlls_v3XX.rar
http://www.mediafire.com/file/tihp2mlwqu10c1o/chapter2dlls_v2.x.x.rar
http://www.mediafire.com/file/ab9qvao3o3jp1b5/chapter3dlls_v3.x.x.rar
http://www.mediafire.com/file/tf014pqm25frrnh/chapter4dlls_v.2.x.x.rar
http://www.mediafire.com/file/z8xpnbzasjrdvgk/chapter5dlls_v2.x.x.rar

**Comment by enumag** [comment]
@P-Chang In the zip for Onikakushi I see scripts like onik_op.txt and onik_015_03.txt. If there are some script changes we need to make (including init.txt and flow.txt) changes, can you commit them to the dll-update branch? (For all chapters of course.)

@ItaloKnox Maybe we should give @P-Chang write access to the repositories?

**Comment by ItaloKnox** [comment]
Yeah, dunno why I didn't do that before. I'll send his invite in a minute.

**Comment by P-Chang** [comment]
@ItaloKnox 
@enumag 

Thank you for inviting.

I'm in system reconstruction. so I'll edit init.txt on web quickly.

onik_op.txt and onik_015_03.txt are just demonstration for "ModNVLinADVMode"

and changing of flow.txt is not necessary without "ModNVLinADVMode" and "ModDisableHotkey"
and "dll-update" branch doesn't have these feature now.

**Comment by enumag** [comment]
There is an issue which never occured to me until now. I'm not sure how the the game works on Linux and Mac but I would assume they don't actually use the same DLL files as the windows version, right? (Can someone confirm?) Which means that we are effectively dropping support for those systems with this realease. Damn.

**Comment by P-Chang** [comment]
I never have Mac and Linux system. I can't support them.
But I validate Mac dll on Windows system, and it worked.

And I checked DLL of Windows and Mac and Linux.

Mac and Linux are same. and differences between Windows and these are only compatibility checking that if system is windows, engine read kernel32.dll on keyhook(but I can't understand what it is)

Probably, vanilla Windows dll work in Mac and Linux.

But I modded Dll on Windows. I know some C# code can't work on Mac and Linux. but I can't check these.

**Comment by enumag** [comment]
Do we have someone to test it? I don't have linux or mac at the moment.

**Comment by Kamil689** [comment]
Hi, I just checked and it seems to be working fine on Linux.

**Comment by enumag** [comment]
@Kamil689 You mean even the new DLLs with our dll-update branches?

**Comment by Kamil689** [comment]
Yes, everything works.

**Comment by enumag** [comment]
@Kamil689 Thanks! Hopefully we can assume that Mac is fine too.

----

Alright, in that case we're ready. I'm very pleased with the update by the way. Previously I never used auto-mode because it skipped part of a voice all the time. Now it works fine and the game feels much smoother as a result.

In fact I pretty much dropped Tatarigoroshi yet again before this update because clicking to continue all the time and pausing the game to fix an error every few minutes was very unpleasant. Of course pausing to fix an error is still there but with ADV-mode + auto-mode + PS3 backgrounds + voices + names + my alternative soundtrack the game finally feels good enough for me to continue. Oh my we really did a LOT of things, didn't we?

So yep, I really love the game as it is right now. Thank you very much @P-Chang for making it possible!

----

@ItaloKnox Now for what you need to do to update everything:

1. Merge dll-update branches to master branches (I can do this for you but doing so will break the installer until we are done with the update. Just tell me when to do it, or do it yourself if you prefer.)
2. Move the necessary resources from @P-Chang zipfiles to some new location. You only need these things from the archives, ignore everything else:
    - `Managed/Assembly-CSharp.dll` (note that this is located outside of StreamingAssets)
    - `StreamingAssets/CG/*` New windo_filter images. Adding them to our CG packs would probably take too much time so maybe just add them to our repos here on GitHub? I'm not sure. Decide where you want them.
    - `StreamingAssets/SE/switchsound/*` You guys had some discussion about these which I didn't pay attention to since I don't care. Is everything ready here?
    - Some new directories in `StreamingAssets`, all of these should be empty for now: `voiceAlt`, `SEAlt`, `BGMAlt`
3. Update the installation scripts in resources repos to download and add those things.
4. Voices now belong to `StreamingAssets/voice`. Either reupload the voice zips (not worth it imo) or rename it in the install script after you unzip the voices
5. When tagging the release, note that this update will once again break existing save files. For the changelog I have the following:

```
- **Fixed auto-mode. Game will no longer auto-continue while a voice is playing.**
- Voice volume is now separate from SE volume. You can adjust it with these keys:
  - M = Increase Voice Volume
  - N = Decrease Voice Volume
  - Left Shift + M = Voice Volume 100
  - Left Shift + N = Voice Volume 0
- Other new hotkeys:
  - **F1 = Toggle NVL/ADV mode**
  - F5 = Quick Save
  - F7 = Quick Load
  - F10 = Flag Monitor
- Fixed in-game icons position.
- Fixed save names on the save & load page.
- Dropped Linux and Mac support (unintended side-effect of the other updates)
```

For Tatarigoroshi you can also add a note about some missing voices and other minor issues.

I intentionally skipped some of the new hotkeys because they have no effect for now.

Also don't forget to update the manual installation section in our documentation accordingly. And you can drop the note about `Auto-hide user interface` in ADV Mode configuration.

----

@P-Chang Can you check the instructions above to see if I forgot anything?

**Comment by P-Chang** [comment]
@Kamil689 
Thank you for feedback. I'll save compatibility as much as I possible in future update.

@enumag 
It is OK.

**Comment by ItaloKnox** [comment]
@enumag 

> Merge dll-update branches to master branches (I can do this for you but doing so will break the installer until we are done with the update. Just tell me when to do it, or do it yourself if you prefer.)

I don't really understand that part, how will it break the installer? The installer is not exactly pulling any masters at this moment, I keep the updates strictly under tags.

> New windo_filter images. Adding them to our CG packs would probably take too much time so maybe just add them to our repos here on GitHub? 

I actually have them uploaded to the resources repo for a while already. Can you get me the images for Kai? If I recall correctly there's a different logo on them. If possible put the images in a folder called CG and push them into [nipah](https://github.com/07th-mod/resources/releases/tag/Nipah) for me. You can go with ``HigurashiKai-Textboxes.zip`` as the filename. I'll merge them with the graphics patches as soon as we get a chance of fixing something that is inside them.

The switchsound thing is ready, I just forgot to show them here. I solved the issues @P-Chang told me before. Should sound good even for the pitch impaired.

I'm a little against creating empty folders but I can let the installer manage that. Somehow I get the feeling we're going to get questions about this.

I'll also need to push a ton of wiki changes so I'm going to set up a page especially for this update. Should be enough to keep everyone up to date about the configuration.

**Comment by enumag** [comment]
> I don't really understand that part, how will it break the installer? The installer is not exactly pulling any masters at this moment, I keep the updates strictly under tags.

It doesn't? It won't break it then. Ok, I'll merge the branches in a moment.

> I actually have them uploaded to the resources repo for a while already. Can you get me the images for Kai? 

At some point we decided to always use the non-kai version since the console-arcs will have both non-kai and kai arcs eventually. If you wish to change that I might be able to dig it up though.

> I'm a little against creating empty folders but I can let the installer manage that. Somehow I get the feeling we're going to get questions about this.

I'm not sure if anything will break if they do not exist. Can you answer this @P-Chang?

**Comment by enumag** [comment]
Oh, no digging needed I guess. I have it right here if you want it: https://github.com/07th-mod/higurashi-patch-compiler/blob/master/data/windo_filter_kai.png

**Comment by P-Chang** [comment]
No audio alt folder probably doesn't break anything.
But if there are empty folder, user can put their own custom sound tarck file easily.

**Comment by ItaloKnox** [comment]
I have all the wiki and installer updates staged, all we need now is to pull the trigger next monday.

I also ask for someone to link me the latest dlls for all chapters. I need to prepare the releases.

**Comment by ItaloKnox** [comment]
Nevermind, @P-Chang sent them earlier. I think I have everything ready for release.

Guess it won't hurt to push them tomorrow.

**Comment by P-Chang** [comment]
@ItaloKnox 
These are newest files.

File that is required in release is included in "Manged".

Other files is not needed now.

http://www.mediafire.com/file/4rt313dr8trawt4/chapter1dlls_v3XX.rar
http://www.mediafire.com/file/tihp2mlwqu10c1o/chapter2dlls_v2.x.x.rar
http://www.mediafire.com/file/ab9qvao3o3jp1b5/chapter3dlls_v3.x.x.rar
http://www.mediafire.com/file/tf014pqm25frrnh/chapter4dlls_v.2.x.x.rar
http://www.mediafire.com/file/z8xpnbzasjrdvgk/chapter5dlls_v2.x.x.rar

**Comment by enumag** [comment]
@ItaloKnox I realized I didn't run the automatic changes for all chapters yet and now I made some mistakes when doing so. Give me some time to sort everything out ok?

**Comment by ItaloKnox** [comment]
No problem, I'm not in a hurry to push these yet. Just let me know when you're done, I'll have to redo the zips.

**Comment by enumag** [comment]
@ItaloKnox Yeah unfortunately :-( Really sorry about that. I should have realized sooner.

**Comment by ItaloKnox** [comment]
Nah, don't worry. It takes only a couple of minutes to pull and make the zips.

**Comment by enumag** [comment]
Glad to hear that.

I'm just about done with the updates. But it would be better if I try and test at least one of the chapters to verify that everything works. I think I'll do Wata because in previous cases it always had the most problems. I'll let you know.

**Comment by P-Chang** [comment]
Great wroks :)

**Comment by ItaloKnox** [comment]
*Now* I think we have everything ready. I'll leave the rest of the day open in case we find something to tweak, so let's leave the release to tomorrow like we planned. 👍

**Comment by enumag** [comment]
@ItaloKnox We could fix [this](https://github.com/07th-mod/tatarigoroshi/pull/37) thing... But I need to test the fix and then @P-Chang would have to upload fixed DLLs for all chapters. Do you wish to wait for that? Otherwise nothing comes to mind.

**Comment by ItaloKnox** [comment]
Yeah, I've been keeping up with that. There's no problem in waiting, we should aim for the best release possible. If this is something that will have to be fixed, then let's fix it as soon as possible instead of deploying another update only to fix that.

**Comment by enumag** [comment]
Alright, we'll let you know when it's ready. Thanks.

**Comment by enumag** [comment]
@ItaloKnox All done. The links to new DLLs are apparently still the same (https://github.com/07th-mod/higurashi-patch-compiler/issues/8). Also update the tata scripts zip, ok?

**Comment by ItaloKnox** [comment]
Ok, everything seems to be ready. I'll start pushing the wiki updates, then the installers (scripts and exes) and then the patches. Hopefully it'll work nicely.

**Comment by ItaloKnox** [comment]
Well, I guess it's official. Great work, guys. We can now certainly say that this is the best version of the patch.

I have to test the installer, hopefully there are no issues. Shouldn't have any unless I missed something really dumb.

**Comment by ItaloKnox** [comment]
Yeah, everything seems to be fine. There's one minor thing that I have to fix in the installer but it's nothing that will break any installs using our new patch. 👍

**Comment by Grelo** [comment]
Guys pls..........

![20171010124220_1](https://user-images.githubusercontent.com/22790067/31382737-f25723c0-adb8-11e7-8145-59a7bddf0af9.jpg)
![20171010124225_1](https://user-images.githubusercontent.com/22790067/31382738-f278807e-adb8-11e7-9450-83c964d2d94d.jpg)

**Comment by ItaloKnox** [comment]
Did you get the new textboxes?

**Comment by Grelo** [comment]
Ok i see.

**Comment by enumag** [comment]
@Grelo If by flicker you mean the fact that the textbox appears for half a second right after you start the game then that's known/unfixable.

**Comment by irlPM** [comment]
@Kamil689 do you still have the files in your pc?

**Comment by Kamil689** [comment]
@irlPM I have the latest Onikakushi DLLs with lipsync, it also seems to include WIP versions
https://mega.nz/#!cNskWbrA!pVqVfvUhsz4h71XP7MRDayAf5igCg_FlWVGNeMnHoIU
